version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todo_microservices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yaroslav8
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo_microservices"]
      interval: 5s
      timeout: 5s
      retries: 10

  tasks:
    container_name: tasks_service
    build: ./tasks
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:yaroslav8@postgres:5432/todo_microservices"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
      users:
        condition: service_started

  users:
    container_name: users_service
    build: ./users
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgresql://postgres:yaroslav8@postgres:5432/todo_microservices"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:  